---
title: "A Bird Filing its Beak: Investigating Swancore's Push Towards Pop"
author: "Richard Weichert"
date: "05-03-2023"
output: 
  flexdashboard::flex_dashboard:
    storyboard: true
    orientation: columns
    vertical_layout: fill
    theme: journal
    
---

```{r setup, include=FALSE}
library(flexdashboard)
library(spotifyr)
library(tidyverse)
library(lubridate)
library(compmus)
library(plotly)
```
Introduction
=================
Column {data-width=800}
-------
This portfolio comprises of statistical investigations into the genre of **Swancore**, a musical hybrid influenced by post-hardcore, mathcore, funk & RnB and, as of late, mainstream pop. I will address 2 questions in this portfolio: the first pertaining to **how the push towards a poppier sound influences the music's reception**, and the second assessing **how this poppier sound informs/is informed by the music's other qualities (such as Key, Mode, Valence, Danceability)**. Having done extensive reading, listening and writing on topics in the fields of musicology, ethnomusicology and acoustic ecology, and being particularily invested in the growth of the Swancore scene, I would like, with this investigation, to combine my interests on a new, statistical frontier.

  In this investigation, artists of interest will include bands **Dance Gavin Dance (DGD)**, **Royal Coda (RC)**, **A Lot Like Birds (ALLB)**, **Stolas**, and **Body Thief (BT)**. 
 
  DGD's long lifespan and reputation for having founded the genre places it front and centre in this investigation - in many regards, the **changes in sound which this band experienced largely define the Swancore genre today**, and as such I expect their changes in musical qualities will be reflected by other bands. However, as DGD ages, RC and other new additions to the roster of Swancore artists have **deviated from the "core" Swancore sound**, and in turn these deviations become a better representation of the genre as a whole. 
  
  BT and Stolas should serve as an interesting parallel to one another, having been formed at approximately the same time with a **distinctly similar sound, even within Swancore**, and each having released **three albums** (the third of each respectively delving further into pop than anything these bands had released before). But, while Stolas separated in 2018, BT continues to remain together to the present day. I hope that this parallel can help **identify how much popularity relies on recentness**.
    
  As a Swancore-adjacent post-hardcore band whose discography stretches actross a far wider range of influences than DGD or any of the other bands in this corpus, I want to identify **if ALLB's popularity is correlated with its proximity of to Swancore/Poppier influences**.

  In working with some of the larger names and pioneers of Swancore, my corpus should serve as a solid overview. However, smaller bands and their more recent contributions to the genre who will not be taken into consideration, which means that *some more recent trends may be overlooked*. Similarily, the newer bands which are being considered may not have enough data to depict trends in sound, or will have so little popularity that it is impossible to tell if musical choices are indicative of what the future may bring (i.e. their relevancy). 

  Tracks of interest (particularily when comparing a presence/lack of pop, funk and RnB influences and their impact on listening statistics) will be *Feels Bad Man* and *Son of Robot* (DGD), *Connector* and *Vanity's Fair* (ALLB), *Becoming the Memory* and *Even If* (RC) and *Bellweather* and *Time & the Sun* (Stolas).
  This being said, click, scroll, read and listen on, and enjoy!

Column {data-width=10}
------------

Column {data-width=190}
------------
### Playlist Links
 
 [Dance Gavin Dance](https://open.spotify.com/playlist/7f9Om6iCmRTzdKRBPD5pcs?si=6036a8c94e6f4a8f)
 
 [Royal Coda](https://open.spotify.com/playlist/4WJ7zh98auBw4xHlFelQ5F?si=ce9e3690534e4d03)
 
 [Stolas](https://open.spotify.com/playlist/75FxeNrnraO5TtfVeSAXWd?si=93495ca4607a4c1b)
 
 [A Lot Like Birds](https://open.spotify.com/playlist/4P2pMy8FAhTRE61Sd10obo?si=7f3f384fa7d34850)
 
 [Body Thief](https://open.spotify.com/playlist/4gsZoA8LJMhQSiHU0ssakc?si=35d16047041b435a)
 
 [Sianvar](https://open.spotify.com/playlist/459ajSShZM6IyPohXIk4DK?si=0f97e5779f424c2f)
 
 [Smaller Artists](https://open.spotify.com/playlist/7muOOsQ7QSYY0e3hqZmX3C?si=69bba0256087480b)
 
``` {r spotify playlists setup, echo = FALSE}
DGDplaylist <- get_playlist_audio_features('','7f9Om6iCmRTzdKRBPD5pcs')
RCplaylist <- get_playlist_audio_features('','4WJ7zh98auBw4xHlFelQ5F')
Stolasplaylist <- get_playlist_audio_features('','75FxeNrnraO5TtfVeSAXWd')
ALLBplaylist <- get_playlist_audio_features('','4P2pMy8FAhTRE61Sd10obo')
SmallSwanplaylist <- get_playlist_audio_features('','7muOOsQ7QSYY0e3hqZmX3C')
BTplaylist <- get_playlist_audio_features('','4gsZoA8LJMhQSiHU0ssakc')
Sianvarplaylist <- get_playlist_audio_features('','459ajSShZM6IyPohXIk4DK')

DGDpopq <- DGDplaylist |>
  summarise(track.name, track.album.name, track.artists, track.album.release_date, track.popularity, danceability, key_name, mode_name)

RCpopq <- RCplaylist |>
  summarise(track.name, track.album.name, track.artists, track.album.release_date, track.popularity, danceability, key_name, mode_name)

Stolaspop_q <- Stolasplaylist |>
  summarise(track.name, track.album.name, track.artists, track.album.release_date, track.popularity, danceability, key_name, mode_name)

ALLBpopq <- ALLBplaylist |>
  summarise(track.name, track.album.name, track.artists, track.album.release_date, track.popularity, danceability, key_name, mode_name)

SmallSwanpopq <- SmallSwanplaylist |>
  summarise(track.name, track.album.name, track.artists, track.album.release_date, track.popularity, danceability, key_name, mode_name)

BTpopq <- BTplaylist |>
  summarise(track.name, track.album.name, track.artists, track.album.release_date, track.popularity, danceability, key_name, mode_name)

Sianvarpopq <- Sianvarplaylist |>
  summarise(track.name, track.album.name, track.artists, track.album.release_date, track.popularity, danceability, key_name, mode_name)
```

Dance Gavin Dance {data-navmenu=Discographies}
===================
Column {data-width=750}
-----------------------------------------------------------------------
### Dance Gavin Dance 

```{r DGDdiscog, fig.width=14, fig.height=8}
plotDGDpop <- ggplot(DGDpopq, aes(x = year(track.album.release_date), y = danceability))

plotDGDpop + geom_point(aes(size = track.popularity, 
                            fill = mode_name, 
                            colour = track.album.name), 
                          shape = 23, stroke = 2, alpha = 0.5) + 
  theme(plot.title = element_text(face = "bold", size = 14),
        plot.caption = element_text(face = "italic", size = 9)) + 
  guides(alpha = "none") + 
  labs(title = "Comparing Danceability and Popularity by Release Date - Dance Gavin Dance", 
       caption = "Source: Spotify", 
       x = "Release Date", 
       y = "Danceability", 
       size = "Popularity", 
       fill = "Mode",
       colour = "Album")
```

Column {data-height=250}
-----------------------------------------------------------------------

### Analysis

Royal Coda {data-navmenu=Discographies}
===================
Column {data-width=750}
---------
### Royal Coda
```{r RCdiscog, fig.width=14, fig.height=8}
plotRCpop <- ggplot(RCpopq, aes(x = year(track.album.release_date), y = danceability))

plotRCpop + geom_point(aes(size = track.popularity, 
                            fill = mode_name, 
                            colour = track.album.name), 
                          shape = 23, stroke = 2, alpha = 0.5) + 
  theme(plot.title = element_text(face = "bold", size = 14),
        plot.caption = element_text(face = "italic", size = 9)) + 
  guides(alpha = "none") + 
  labs(title = "Comparing Danceability and Popularity by Release Date - Royal Coda", 
       caption = "Source: Spotify", 
       x = "Release Date", 
       y = "Danceability", 
       size = "Popularity", 
       fill = "Mode",
       colour = "Album")
```
Column {data=width=250}
----------
Column {data-width=250}
### Analysis


Stolas {data-navmenu=Discographies}
===================
Column {data-width=750}
-----------
### Stolas
```{r Stolasdiscog, fig.width=14, fig.height=8}
plotStolaspop <- ggplot(Stolaspop_q, aes(x = year(track.album.release_date), y = danceability))

plotStolaspop + geom_point(aes(size = track.popularity, 
                            fill = mode_name, 
                            colour = track.album.name), 
                          shape = 23, stroke = 2, alpha = 0.5) + 
  theme(plot.title = element_text(face = "bold", size = 14),
        plot.caption = element_text(face = "italic", size = 9)) + 
  guides(alpha = "none") + 
  labs(title = "Comparing Danceability and Popularity by Release Date - Stolas", 
       caption = "Source: Spotify", 
       x = "Release Date", 
       y = "Danceability", 
       size = "Popularity", 
       fill = "Mode",
       colour = "Album")
```
Column {data-width=250}
------------------------
### Analysis

Body Thief {data-navmenu=Discographies}
===================
Column {data-width=750}
----------
### Body Thief
```{r BTdiscog, fig.width=14, fig.height=8}
plotBTpop <- ggplot(BTpopq, aes(x = year(track.album.release_date), y = danceability))

plotBTpop + geom_point(aes(size = track.popularity, 
                            fill = mode_name, 
                            colour = track.album.name), 
                          shape = 23, stroke = 2, alpha = 0.5) + 
  theme(plot.title = element_text(face = "bold", size = 14),
        plot.caption = element_text(face = "italic", size = 9)) + 
  guides(alpha = "none") + 
  labs(title = "Comparing Danceability and Popularity by Release Date - Body Thief", 
       caption = "Source: Spotify", 
       x = "Release Date", 
       y = "Danceability", 
       size = "Popularity", 
       fill = "Mode",
       colour = "Album")
```
Column {data-width=250}
--------------
### Analysis

Sianvar {data-navmenu=Discographies}
===================
Column {data-width=750}
--------
### Sianvar
```{r Sianvardiscog, fig.width=14, fig.height=8}
plotSianvarpop <- ggplot(Sianvarpopq, aes(x = year(track.album.release_date), y = danceability))

plotSianvarpop + geom_point(aes(size = track.popularity, 
                            fill = mode_name, 
                            colour = track.album.name), 
                          shape = 23, stroke = 2, alpha = 0.5) + 
  theme(plot.title = element_text(face = "bold", size = 14),
        plot.caption = element_text(face = "italic", size = 9)) + 
  guides(alpha = "none") + 
  labs(title = "Comparing Danceability and Popularity by Release Date - Sianvar", 
       caption = "Source: Spotify", 
       x = "Release Date", 
       y = "Danceability", 
       size = "Popularity", 
       fill = "Mode",
       colour = "Album")
```
Column {data-width=250}
-------------
### Analysis
Dance Gavin Dance: Summertime Gladness {data-navmenu=Chromagrams/Cepstograms}
============

Column {data-width=330}
----------
### Chromagram
``` {r DGDcromagram, echo = FALSE}
Summertime <-
get_tidy_audio_analysis("639JHsrGV8A9qUYSXhOwsw") |>
  select(segments) |>
  unnest(segments) |>
  select(start, duration, pitches)

Summertime |>
  mutate(pitches = map(pitches, compmus_normalise, "euclidean")) |>
  compmus_gather_chroma() |> 
  ggplot(
    aes(
      x = start + duration / 2,
      width = duration,
      y = pitch_class,
      fill = value
    )
  ) +
  geom_tile() +
  labs(x = "Time (s)", y = NULL, fill = "Magnitude", title = "Pitch Analysis of Summertime Gladness (Dance Gavin Dance, 2017)") +
  theme_minimal() +
  scale_fill_viridis_c()
```

Column {data-width=340}
---------
This page hosts two graphical representations of [Summertime Gladness](https://open.spotify.com/track/639JHsrGV8A9qUYSXhOwsw), one of Dance Gavin Dance's most popular singles, and their most danceable according to Spotify's API. [analysis pending]

Column {data-width=330}
--------
### Cepstogram
``` {r DGDcepstogram, echo = FALSE}
Summertimetimbre <-
get_tidy_audio_analysis("639JHsrGV8A9qUYSXhOwsw") |> 
  compmus_align(beats, segments) |>                     
  select(beats) |>                                      
  unnest(beats) |>                                      
  mutate(
    pitches =
      map(segments,
          compmus_summarise, pitches,
          method = "rms", norm = "euclidean"              
      )
  ) |>
  mutate(
    timbre =
      map(segments,
          compmus_summarise, timbre,
          method = "rms", norm = "euclidean"              
      )
  )

Summertimetimbre |>
  compmus_gather_timbre() |>
  ggplot(
    aes(
      x = start + duration / 2,
      width = duration,
      y = basis,
      fill = value
    )
  ) +
  geom_tile() +
  labs(x = "Time (s)", y = NULL, fill = "Magnitude", title = "Timbre Analysis of Summertime Gladness (Dance Gavin Dance, 2017)") +
  scale_fill_viridis_c() +                              
  theme_classic()
```

The Push to Pop: A Timbre Analysis
===============

Column {data-width=800}
----------------------------
``` {r, echo=FALSE}
swancore <-
  get_playlist_audio_features(
    "thesoundsofspotify",
    "2NAM4VUbbZi2t1y3TfJsvH"
  ) |>
  slice(1:30) |>
  add_audio_analysis()
pphc <-
  get_playlist_audio_features(
    "thesoundsofspotify",
    "4tzo97AF7cGmRpYnnMosHP"
  ) |>
  slice(1:30) |>
  add_audio_analysis()
funkrock <- 
  get_playlist_audio_features(
    "", "2v7uYvX2h5hNSukaqp9LCb"
  ) |>
  slice(1:30) |>
  add_audio_analysis()
kpop <-
  get_playlist_audio_features(
    "", "3T1Rft817cZ3pguTvaWaz3"
  ) |>
  slice(1:30) |>
  add_audio_analysis()
pop <-
  get_playlist_audio_features(
    "", "6gS3HhOiI17QNojjPuPzqc"
  ) |>
  slice(1:30) |>
  add_audio_analysis()

postcore <-
  swancore |>
  mutate(genre = "Swancore") |>
  bind_rows(pphc |> mutate(genre = "Progressive Post Hardcore")) |>
  bind_rows(funkrock |> mutate(genre = "Funk Rock")) |>
  bind_rows(kpop |> mutate(genre = "K-Pop")) |>
  bind_rows(pop |> mutate(genre = "Pop")) |>
  mutate(genre = fct_relevel(genre, c("Progressive Post Hardcore", "Swancore", "Funk Rock", "K-Pop", "Pop")))

postcore |>
  mutate(
    timbre =
      map(
        segments,
        compmus_summarise,
        timbre,
        method = "mean"
      )
  ) |>
  select(genre, timbre) |>
  compmus_gather_timbre() |>
  ggplot(aes(x = basis, y = value, fill = genre)) +
  geom_violin() +
  scale_fill_viridis_d() +
  labs(x = "Spotify Timbre Coefficients", y = "", fill = "Genre")
```

Column {data-width=200}
--------------

### Analysis

